[build]
  
  command = "npm run build"
  
  publish = "build"

  [build.environment]
  PYTHON_VERSION = "3.8"


[[redirects]]
  from = "/api/*"
  to = "https://pinchez420.pythonanywhere.com/"
  status = 200
  force = true
  
