[build]
  publish = "frontend"  
  command = "echo 'No build step required'"  

[[redirects]]
  from = "/api/*"
  to = "https://pinchez420.pythonanywhere.com/"  
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


[build.environment]

